# Generated by Django 3.2.9 on 2021-12-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_number', models.IntegerField()),
                ('version', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'instrument_group',
            },
        ),
    ]
